name: test
channels:
  - conda-forge
dependencies:
    # Core
  - python
  - pyyaml
  - py-cpuinfo
  - psutil
  - qcelemental >=0.12.0
  - pydantic>=2.0.0
  - pydantic-settings

    # Testing
  - pytest
  - pytest-cov
  - codecov
