coverage:
  ignore:
    - qcengine/programs/util/.*
    - qcengine/programs/cfour/.*
    - qcengine/programs/gamess/.*
    - setup.py
  status:
    patch: false
    project:
      default:
        threshold: 80%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: once
  flags: null
  paths: null
