import json
import os
import subprocess
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import pytest

_DATA_PATH = Path(__file__).parent.resolve() / "qcengine" / "tests" / "qcschema_instances"
_VALIDATION_TEST = "test_zqcschema.py"


def pytest_addoption(parser):
    group = parser.getgroup("qcschema examples")
    group.addoption(
        "--qcschema-examples",
        action="store_true",
        help="collect QCSchema examples created by the test suite",
    )
    group.addoption(
        "--validate-qcschema-examples",
        action="store_true",
        help="validate QCSchema examples generated by a previous test run",
    )


def pytest_configure(config):
    generate = config.getoption("--qcschema-examples")
    validate = config.getoption("--validate-qcschema-examples")
    if generate and validate:
        raise pytest.UsageError("--qcschema-examples and --validate-qcschema-examples are separate modes")
    if generate:
        os.environ["QCSCHEMA_EXAMPLES_GENERATE"] = "1"
    else:
        os.environ.pop("QCSCHEMA_EXAMPLES_GENERATE", None)


def pytest_sessionstart(session):
    if session.config.getoption("--qcschema-examples"):
        for example in _DATA_PATH.rglob("*.json"):
            example.unlink()


def pytest_collection_modifyitems(config, items):
    validate = config.getoption("--validate-qcschema-examples")
    selected = []
    deselected = []
    for item in items:
        is_validation = item.path.name == _VALIDATION_TEST
        if is_validation == validate:
            selected.append(item)
        else:
            deselected.append(item)
    if deselected:
        config.hook.pytest_deselected(items=deselected)
    items[:] = selected


def _git_value(*args):
    try:
        return subprocess.check_output(["git", *args], cwd=_DATA_PATH, text=True, stderr=subprocess.DEVNULL).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def pytest_sessionfinish(session, exitstatus):
    if not session.config.getoption("--qcschema-examples"):
        return

    import qcelemental
    import qcengine

    examples = sorted(_DATA_PATH.glob("v*/*/*.json"))
    counts = Counter((path.parts[-3], path.parts[-2]) for path in examples)
    manifest = {
        "format_version": 1,
        "origin": "qcengine",
        "qcengine_version": qcengine.__version__,
        "qcelemental_version": qcelemental.__version__,
        "source_commit": os.environ.get("GITHUB_SHA") or _git_value("rev-parse", "HEAD"),
        "source_branch": os.environ.get("GITHUB_REF_NAME") or _git_value("branch", "--show-current"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pytest_exitstatus": exitstatus,
        "example_count": len(examples),
        "counts": {
            version: {
                model: count for (item_version, model), count in sorted(counts.items()) if item_version == version
            }
            for version in ("v1", "v2")
        },
    }
    _DATA_PATH.mkdir(parents=True, exist_ok=True)
    (_DATA_PATH / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
