name: qcengine-docs
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - sphinx <4
    - sphinx_rtd_theme
    - sphinx-automodapi
    - graphviz
    
      # QCEngine depends
    - numpy
    - pydantic >=0.30.1
    - qcelemental >=0.9.0

    - pip:
      - git+git://github.com/MolSSI/qcarchive-sphinx-theme#egg=qcarchive_sphinx_theme
